### ISSUE TITLE
ScrollView ref not returning scrollTo method

### ISSUE THREAD

**Issue by joeonmars** [tamagui/tamagui#1391]
Same as reported in https://github.com/tamagui/tamagui/issues/823. Still an open issue when running in iOS/Android.

**Code to reproduce:**
```
import { useRef, useEffect } from 'react'
import { ScrollView } from 'tamagui'

const Test = () => {

  const scrollViewRef = useRef()

  useEffect(() => {
    // The below returns undefined
    console.log(scrollViewRef.current.scrollTo)
  }, [])

  return <ScrollView ref={scrollViewRef} />
}

export default Test
```

**Expected Behavior:**
Library users can extract [all three methods (flashScrollIndicators, scrollTo, scrollToEnd)](https://reactnative.dev/docs/scrollview#methods) of `ScrollView` from its ref

**Tamagui Version**
Reproducible in both `1.36.6` and `1.38.4` versions of tamagui

**Comment by natew** [comment]
fixed in v1.39.2 i think due to flattening accidentaly i verified in sandbox

**Comment by joeonmars** [comment]
Verified the fix in v.1.39.2. Thanks for addressing it so promptly 💯

**Comment by joeonmars** [comment]
@natew Looking further into the fix, it looks like `Group` (with `scrollable` prop setting https://github.com/tamagui/tamagui/blob/48ec3691166f7078c3fa32e78bd4d0fe0d11a44f/packages/group/src/Group.tsx#L271) and its extension components like `Tab.List` still not getting the methods available.

**Comment by natew** [comment]
100%, will fix this (again) soon. @baronha good starter ticket

**Comment by baronha** [comment]
> IMHO, this should be re-opened as this issue still persists...

Please check the latest version v1.121.7.  I verified in kitchen-sink

<img width="492" alt="Screenshot 2025-01-10 at 23 29 53" src="https://github.com/user-attachments/assets/c4c969d0-d4d7-4a79-8841-87e1e2ee64eb" />
