### ISSUE TITLE
Expo  eas build fails Unable to resolve module @tamagui/use-did-finish-ssr

### ISSUE THREAD

**Issue by sevketaydogdu** [tamagui/tamagui#2588]
### Current Behavior

❌ Metro encountered an error:
Unable to resolve module @tamagui/use-did-finish-ssr from /Users/expo/workingdir/build/node_modules/@tamagui/portal/dist/cjs/GorhomPortal.native.js: @tamagui/use-did-finish-ssr could not be found within the project or in these directories:
  node_modules/@tamagui/portal/node_modules
  node_modules
  
  32 | });
  33 | module.exports = __toCommonJS(GorhomPortal_exports);
> 34 | var import_jsx_runtime = require("react/jsx-runtime"), import_constants = require("@tamagui/constants"), import_core = require("@tamagui/core"), import_use_did_finish_ssr = require("@tamagui/use-did-finish-ssr"), import_react = __toESM(require("react"));
     |                                                                                                                                                                                       ^
  35 | function _array_like_to_array(arr, len) {
  36 |   (len == null || len > arr.length) && (len = arr.length);
  37 |   for (var i = 0, arr2 = new Array(len); i < len; i++)
Learn more: https://docs.expo.dev/build-reference/troubleshooting

The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ app.manifest\ for\ expo-updates /Users/expo/Library/Developer/Xcode/DerivedData/Politicca-fprhmrwkmnczyzabqmmsirgtncml/Build/Intermediates.noindex/ArchiveIntermediates/Politicca/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/EXUpdates.build/Script-46EB2E00034F70.sh (in target 'EXUpdates' from project 'Pods')
(1 failure)

### Tamagui Version

```markdown
"tamagui": "^1.39.6",
```

### Platform (Web, iOS, Android)

```markdown
ios
```

### Reproduction

```markdown
i dont have code sandbox
```

### System Info

```markdown
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 59.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /usr/local/bin/npm
    bun: 1.0.35 - /opt/homebrew/bin/bun
    Watchman: 2024.04.22.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 124.0.6367.78
    Edge: 124.0.2478.51
    Safari: 17.4.1
  npmPackages:
    @babel/core: ^7.20.0 => 7.24.4 
    @babel/plugin-proposal-export-namespace-from: ^7.18.9 => 7.18.9 
    @expo/metro-config: ^0.10.7 => 0.10.7 
    @expo/vector-icons: ^13.0.0 => 13.0.0 
    @fawazahmed/react-native-read-more: ^3.0.3 => 3.0.3 
    @flyerhq/react-native-link-preview: ^1.6.0 => 1.6.0 
    @hookform/resolvers: ^3.2.0 => 3.3.4 
    @invertase/react-native-apple-authentication: ^2.3.0 => 2.3.0 
    @likashefqet/react-native-image-zoom: ^2.1.1 => 2.2.0 
    @logrocket/react-native: ^1.30.0 => 1.33.2 
    @miblanchard/react-native-slider: ^2.3.1 => 2.6.0 
    @microsoft/signalr: ^7.0.12 => 7.0.14 
    @react-native-async-storage/async-storage: 1.18.2 => 1.18.2 
    @react-native-community/netinfo: 9.3.10 => 9.3.10 
    @react-native-community/slider: ^4.5.1 => 4.5.2 
    @react-native-firebase/analytics: ^18.7.1 => 18.9.0 
    @react-native-firebase/app: ^18.7.1 => 18.9.0 
    @react-native-firebase/auth: ^18.8.0 => 18.9.0 
    @react-native-google-signin/google-signin: ^10.1.1 => 10.1.2 
    @react-navigation/drawer: ^6.6.3 => 6.6.15 
    @react-navigation/material-top-tabs: ^6.6.3 => 6.6.13 
    @react-navigation/native: ^6.0.2 => 6.1.17 
    @reduxjs/toolkit: ^1.9.5 => 1.9.7 
    @sentry/react-native: 5.10.0 => 5.10.0 
    @shopify/flash-list: 1.4.3 => 1.4.3 
    @tamagui/animations-react-native: ^1.39.6 => 1.95.1 
    @tamagui/babel-plugin: ^1.39.6 => 1.95.1 
    @tamagui/config: ^1.39.6 => 1.95.1 
    @tamagui/constants: ^1.95.1 => 1.95.1 
    @tamagui/core: ^1.95.1 => 1.95.1 
    @tamagui/font-inter: ^1.39.6 => 1.95.1 
    @tamagui/theme-base: ^1.39.6 => 1.95.1 
    @tanstack/eslint-plugin-query: ^5.8.4 => 5.28.11 
    @types/humanize-duration: ^3.27.1 => 3.27.4 
    @types/lodash: ^4.14.199 => 4.17.0 
    @types/react: ~18.2.14 => 18.2.79 
    @types/uuid: ^9.0.8 => 9.0.8 
    axios: ^1.6.7 => 1.6.8 
    babel-loader: ^8.3.0 => 8.3.0 
    babel-plugin-transform-inline-environment-variables: ^0.4.4 => 0.4.4 
    eslint: ^8.56.0 => 8.57.0 
    eslint-config-universe: ^12.0.0 => 12.0.1 
    expo: ^49.0.6 => 49.0.23 
    expo-application: ~5.3.0 => 5.3.1 
    expo-av: ~13.4.1 => 13.4.1 
    expo-build-properties: ~0.8.3 => 0.8.3 
    expo-config-plugin-ios-share-extension: ^0.0.4 => 0.0.4 
    expo-constants: ~14.4.2 => 14.4.2 
    expo-dev-client: ~2.4.6 => 2.4.13 
    expo-device: ~5.4.0 => 5.4.0 
    expo-doctor: ^1.1.3 => 1.5.0 
    expo-document-picker: ~11.5.4 => 11.5.4 
    expo-file-system: ~15.4.4 => 15.4.5 
    expo-font: ~11.4.0 => 11.4.0 
    expo-haptics: ~12.4.0 => 12.4.0 
    expo-image: ~1.3.2 => 1.3.5 
    expo-image-picker: ~14.3.2 => 14.3.2 
    expo-insights: ~0.2.0 => 0.2.0 
    expo-linear-gradient: ~12.3.0 => 12.3.0 
    expo-linking: ~5.0.2 => 5.0.2 
    expo-localization: ~14.3.0 => 14.3.0 
    expo-notifications: ~0.20.1 => 0.20.1 
    expo-router: ^2.0.14 => 2.0.15 
    expo-secure-store: ~12.3.1 => 12.3.1 
    expo-splash-screen: ~0.20.5 => 0.20.5 
    expo-sqlite: ~11.3.3 => 11.3.3 
    expo-status-bar: ~1.6.0 => 1.6.0 
    expo-store-review: ~6.4.0 => 6.4.0 
    expo-system-ui: ~2.4.0 => 2.4.0 
    expo-updates: ~0.18.11 => 0.18.19 
    expo-video-thumbnails: ~7.4.0 => 7.4.0 
    expo-web-browser: ~12.3.2 => 12.3.2 
    fast-xml-parser: ^4.2.7 => 4.3.6 
    humanize-duration: ^3.30.0 => 3.32.0 
    i18n-js: ^4.3.2 => 4.4.3 
    jest: ^29.2.1 => 29.7.0 
    jwt-decode: ^3.1.2 => 3.1.2 
    lodash: ^4.17.21 => 4.17.21 
    moment: ^2.29.4 => 2.30.1 
    node-fetch: ^2.6.1 => 2.7.0 
    patch-package: ^8.0.0 => 8.0.0 
    prettier: ^3.2.4 => 3.2.5 
    react: 18.2.0 => 18.2.0 
    react-hook-form: ^7.45.4 => 7.51.3 
    react-native: 0.72.10 => 0.72.10 
    react-native-avoid-softinput: ^4.0.1 => 4.0.2 
    react-native-gesture-handler: ~2.12.0 => 2.12.1 
    react-native-get-random-values: ^1.10.0 => 1.11.0 
    react-native-mmkv: ^2.10.2 => 2.12.2 
    react-native-pager-view: 6.2.0 => 6.2.0 
    react-native-reanimated: ~3.3.0 => 3.3.0 
    react-native-receive-sharing-intent: ^2.0.0 => 2.0.0 
    react-native-render-html: ^6.3.4 => 6.3.4 
    react-native-safe-area-context: 4.6.3 => 4.6.3 
    react-native-screens: ~3.22.0 => 3.22.1 
    react-native-slider: ^0.11.0 => 0.11.0 
    react-native-svg: 13.9.0 => 13.9.0 
    react-native-svg-transformer: ^1.1.0 => 1.3.0 
    react-native-tab-view: ^3.5.2 => 3.5.2 
    react-native-xml2js: ^1.0.3 => 1.0.3 
    react-redux: ^8.1.2 => 8.1.3 
    react-test-renderer: 18.2.0 => 18.2.0 
    redux-persist: ^6.0.0 => 6.0.0 
    sentry-expo: ~7.1.0 => 7.1.1 
    swr: ^2.2.0 => 2.2.5 
    tamagui: ^1.39.6 => 1.95.1 
    typescript: ^5.1.3 => 5.4.5 
    whatwg-fetch: ^3.6.2 => 3.6.20 
    yup: ^1.2.0 => 1.4.0
```

**Comment by PrimulaX** [comment]
Same

**Comment by TheEhsanSarshar** [comment]
it seems that `@tamagui/use-did-finish-ssr` is missing

try to use the latest version of tamagui, or install `@tamagui/use-did-finish-ssr` to make sure it's the same version as your other dependencies.

**Comment by kotani123** [comment]
I have the same issue when building locally with iOS. I didn’t have this error when building the same project a week ago. perhaps a issue with 1.95.0 or 1.95.1?

**Comment by ParthShrivastav** [comment]
Same

**Comment by TheEhsanSarshar** [comment]
ok I'll check that
for now, as a workaround install that missing dependency manually

**Comment by ParthShrivastav** [comment]
> ok I'll check that for now, as a workaround install that missing dependency manually

Tried doing it, but it gives an error saying it can't be installed in mac

**Comment by sevketaydogdu** [comment]
i can note that it works when i clear and prebuild from scratch and run on local, but eas build gives error.
On the other hand when i was trying clear projeact setup tamagui and other deps it gave me same error on local and tried again with same dependencies it builded. I dont understand what is problem 😢

**Comment by PrimulaX** [comment]
@TheEhsanSarshar It gives another error, there is no workaround so far.

**Comment by TheEhsanSarshar** [comment]
@PrimulaX make sure your tamagui dependencies are same versions

**Comment by PrimulaX** [comment]
@TheEhsanSarshar Yep, I checked all of that stuff.

**Comment by kotani123** [comment]
I have also tried setting all of the  versions to the same, and included @tamagui/use-did-finish-ssr as well. With the inclusion, I'm also getting a different error now, as @PrimulaX has mentioned.

**Comment by sambulosenda** [comment]
I have this same error.  tried everything mentioned above no solution

**Comment by milos201** [comment]
I have the same issue. Installing `@tamagui/use-did-finish-ssr` fixed it, but it caused other issues for android. App crashes on startup because it can't find `useMemo` in `@tamagui/web`.

**Comment by TheEhsanSarshar** [comment]
just built a project and used `Tamagui free starter`. everything seems to be working fine
btw I haven't used `eas build`, I built it locally
is it on tamagui expo router starter?

**Comment by milos201** [comment]
For me, it's RN CLI. No expo at all. (toasts don't work at all because they require expo)

**Comment by natew** [comment]
This one was simple we left out the dependency in `@tamagui/portal`, I published `1.95.2` with a fix. You can also just add that dependency to your app I believe.

**Comment by natew** [comment]
Er, it's going out now not quite out yet.

**Comment by natew** [comment]
Should be fixed in 4301766b7734cdff56184c2a192cb991a4ca2fb5

**Comment by arekkubaczkowski** [comment]
@natew  @TheEhsanSarshar it seems like it caused another error. 
<img width="1447" alt="Screenshot 2024-04-28 at 18 22 11" src="https://github.com/tamagui/tamagui/assets/18654447/6e85b376-216c-4bf8-b589-eeab3033bb94">

**Comment by milos201** [comment]
> @natew @TheEhsanSarshar it seems like it caused another error. <img alt="Screenshot 2024-04-28 at 18 22 11" width="1447" src="https://private-user-images.githubusercontent.com/18654447/326272491-6e85b376-216c-4bf8-b589-eeab3033bb94.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzMjI3OTksIm5iZiI6MTcxNDMyMjQ5OSwicGF0aCI6Ii8xODY1NDQ0Ny8zMjYyNzI0OTEtNmU4NWIzNzYtMjE2Yy00YmY4LWI1ODktZWVhYjMwMzNiYjk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDE2NDEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOTQ1NDdjYjUyY2VhNjZjNTRiMDk4NDE3Yzk2ZjNlYzlmNzJiOTE4Yzk4NTY5YmRhMzEyMTUzZTYzOTNhZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1_oCeTf5Z3yVVv-9g3nfULFfxAgs46qOS7C8f3nT7cE">

Same for me. I just get it for `useMemo`.

**Comment by arekkubaczkowski** [comment]
I tried downgrading tamagui version and still happens, my project is completely broken :(

**Comment by milos201** [comment]
> I tried downgrading tamagui version and still happens, my project is completely broken :(

Same. For me, iOS works fine. It only happens on android production builds. But same thing, `@tamagui/web` package… `useMemo` tho.

**Comment by arekkubaczkowski** [comment]
I think I found the cause:
https://github.com/expo/expo/issues/28471#issuecomment-2080094893

**Comment by milos201** [comment]
> I think I found the cause: [expo/expo#28471 (comment)](https://github.com/expo/expo/issues/28471#issuecomment-2080094893)

I don't use expo and I still get the same issue in `TamaguiProvider` component.

**Comment by arekkubaczkowski** [comment]
just follow the steps from the comment :) latest tamagui also relies on react-dom@18.3.1 so now you probably have two different versions of react-dom which are not compatible with each other.

**Comment by arekkubaczkowski** [comment]
I guess that tamagui's packages need to be updated to use 18.2.0 explicitly instead of `^18.2.0`
@natew

**Comment by natew** [comment]
This isn't a tamagui issue, our dependencies are defined entirely as `^18.2.0` - not all issues are tamagui! lol

https://github.com/tamagui/tamagui/issues/2595#issuecomment-2081614513

**Comment by PrimulaX** [comment]
Why did this happen without any changes? I haven’t updated any package and got this error

**Comment by PrimulaX** [comment]
So there is different version of react-dom in tamagui
<img width="713" alt="image" src="https://github.com/tamagui/tamagui/assets/16132259/054d2720-2112-4daa-a19f-616bbf053119">

**Comment by arekkubaczkowski** [comment]
I recommend to bump react & react-dom versions in your repo's :) There are no any breaking changes so seems to makes more sense to have it up2date

**Comment by milos201** [comment]
I'm on latest version of react, and since it's react native, there is no react-dom.

**Comment by arekkubaczkowski** [comment]
@milos201 please check how many versions of react you have.

**Comment by milos201** [comment]
```
yarn why v1.22.22
[1/4] 🤔  Why do we have the module "react"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react@18.3.1"
info Has been hoisted to "react"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "388KB"
info Disk size with unique dependencies: "420KB"
info Disk size with transitive dependencies: "448KB"
info Number of shared dependencies: 2
=> Found "@tamagui/animations-css#react@18.2.0"
info This module exists because "@tamagui#config#@tamagui#animations-css" depends on it.
info Disk size without dependencies: "388KB"
info Disk size with unique dependencies: "420KB"
info Disk size with transitive dependencies: "448KB"
info Number of shared dependencies: 2
=> Found "@tamagui/animations-moti#react@18.2.0"
info This module exists because "@tamagui#config#@tamagui#animations-moti" depends on it.
info Disk size without dependencies: "388KB"
info Disk size with unique dependencies: "420KB"
info Disk size with transitive dependencies: "448KB"
info Number of shared dependencies: 2
=> Found "@tamagui/web#react@18.2.0"
info This module exists because "@tamagui#config#@tamagui#web" depends on it.
info Disk size without dependencies: "388KB"
info Disk size with unique dependencies: "420KB"
info Disk size with transitive dependencies: "448KB"
info Number of shared dependencies: 2
✨  Done in 0.23s.
```
