### ISSUE TITLE
[bug] testID on Input component

### ISSUE THREAD

**Issue by lobor** [tamagui/tamagui#467]
`testID` usage for Input component not add data-testid on dom. work for Button but not Input

**Comment by christianalares** [comment]
I have the same issue. I created a bug for this here: https://github.com/tamagui/tamagui/issues/354
At the time I thought it was a general problem during build but this is actually a problem for Input component during build.
Currently running `1.1.5`. The repro in the link to my other issue should still be applicable

**Comment by natew** [comment]
Still issue? We've fixed and tested testID since.

**Comment by lobor** [comment]
I test it this week end

**Comment by lobor** [comment]
I have tested and testID not add in dom

**Comment by lobor** [comment]
I re test today, not working on 1.5.17

**Comment by kpoelhekke** [comment]
I'm still experiencing this issue on `1.93.3`.  `testID` is forwarded for dev builds, but is removed on production builds. Hence all E2E tests depending on it fail.
