### ISSUE TITLE
Can't start web app when SolitoImage is used by a component 

### ISSUE THREAD

**Issue by la55u** [tamagui/tamagui#846]
When trying to start the nextjs app with `yarn web` from the root of the monorepo, I get the following error:

```

Tamagui Webpack Loader Error:
   createCSSVariable expected string: undefined
Error: createCSSVariable expected string: undefined
    at createCSSVariable (/home/la/Projects/tamagui-bug/node_modules/@tamagui/core-node/dist/index.js:5838:17)
    at variableToCSS (/home/la/Projects/tamagui-bug/node_modules/@tamagui/core-node/dist/index.js:10563:63)
    at /home/la/Projects/tamagui-bug/node_modules/@tamagui/core-node/dist/index.js:11016:78
    at createTamagui (/home/la/Projects/tamagui-bug/node_modules/@tamagui/core-node/dist/index.js:11086:9)
    at loadTamagui (/home/la/Projects/tamagui-bug/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:155:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.load [as loadTamagui] (/home/la/Projects/tamagui-bug/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:92:42)
    at async extractToClassNames (/home/la/Projects/tamagui-bug/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:78:3)
    at async Object.loader2 (/home/la/Projects/tamagui-bug/node_modules/tamagui-loader/dist/cjs/loader.js:62:23)

Missing theme, an error occurred when importing your config
Got config: [Function (anonymous)] {
  displayName: 'ProxyWorm - Check excludeReactNativeWebExports',
  _isProxyWorm: true
}
Looking for theme: displayName

```

## Reproduction
Repo: https://github.com/la55u/tamagui-solitoimage-repro
1. run `yarn`
2. run `yarn web`
3. you should see the script exited with the error above
 
Note that the only thing in the ui package is a simple component that uses SolitoImage. When I try to replace that with any other tamagui component it works.
Not sure if this is a tamagui or solito error, but posting it here because it's included in the starter so it's expected to work. 

Any help would be appreciated, thank you, love Tamagui <3

**Comment by deggertsen** [comment]
Same issue here. When I import and use SolitoImage in my UI (creating an Image wrapper component) I get this when trying to run the web app.

```
Tamagui Webpack Loader Error:
   createCSSVariable expected string: undefined
Error: createCSSVariable expected string: undefined
    at createCSSVariable (/node_modules/@tamagui/core-node/dist/index.js:5838:17)
    at variableToCSS (/node_modules/@tamagui/core-node/dist/index.js:10564:63)
    at /node_modules/@tamagui/core-node/dist/index.js:11017:78
    at createTamagui (/node_modules/@tamagui/core-node/dist/index.js:11087:9)
    at loadTamagui (/node_modules/@tamagui/static/dist/cjs/extractor/loadTamagui.js:155:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.load [as loadTamagui] (/node_modules/@tamagui/static/dist/cjs/extractor/createExtractor.js:92:42)
    at async extractToClassNames (/node_modules/@tamagui/static/dist/cjs/extractor/extractToClassNames.js:78:3)
    at async Object.loader2 (/node_modules/tamagui-loader/dist/cjs/loader.js:62:23)
Missing theme, an error occurred when importing your config
Got config: [Function (anonymous)] {
  displayName: 'ProxyWorm - Check excludeReactNativeWebExports',
  _isProxyWorm: true
}
Looking for theme: displayName
```

As soon as I swap out SolitoImage for Tamagui's Image component everything works fine again. Any ideas what might be happening here?

This is what my component looks like:

```
import React from 'react'
import { ImageResizeMode } from 'react-native/types'
import { SolitoImage } from 'solito/image'

import { Box, BoxProps } from './Box'

export function Image({
  alt,
  src,
  resizeMode,
  ...props
}: { alt: string; src: string; resizeMode?: ImageResizeMode } & BoxProps) {
  return (
    <Box {...props}>
      <SolitoImage alt={alt} src={src} resizeMode={resizeMode} fill />
    </Box>
  )
}
```

**Comment by stoickeyboard** [comment]
A shot in the dark her but do you guys have ```images: {}``` in your next.config.js? It looks like SolitoImage requires that.

From SolitoImage Docs:
```
Next.js
solito/image requires Next.js 13+.

Add the images configuration to your next.config.js:

module.exports = {
  images: {},
}
```

**Comment by deggertsen** [comment]
> A shot in the dark here but do you guys have `images: {}` in your next.config.js? It looks like SolitoImage requires that.
> 
> From SolitoImage Docs:
> 
> ```
> Next.js
> solito/image requires Next.js 13+.
> 
> Add the images configuration to your next.config.js:
> 
> module.exports = {
>   images: {},
> }
> ```

Doesn't fix the issue unfortunately.

**Comment by deggertsen** [comment]
> I'm using `SolitoImage` just fine on BeatGig's site, so I'm surprised that it's giving issues. Are you on Solito 3? And Next.js 13.1+?

Looks like I'm on 13.0.6 of Next with Solito 3. I will try upgrading Next soon to see if that fixes it.

**Comment by deggertsen** [comment]
Just an update here. I tried using expo-image instead of Solito and ran into the same issue. So it seems like this is a compatibility issue with expo-image rather than Solito and Tamagui.

**Comment by izakfilmalter** [comment]
Ya I have the same issue with expo-image or solito.

**Comment by deggertsen** [comment]
I managed to get it working with this workaround.
Create an Image.native.tsx file and create a wrapper for SolitoImage there.
Create an Image.tsx file and create a wrapper for NextImage there.

For some reason when using Image.web.tsx I still get the errors from SolitoImage and Tamagui. Seems like there may be something with Tamagui that is loading in the root file, which causes issues when there is a compatibility issue with web vs native. That's my guess at least.

**Comment by nandorojo** [comment]
Can I see your web file? Is it using `unstable_createElement` from RNW? Are you using `react-native-web-lite`? I'm thinking that might be the cause.

**Comment by deggertsen** [comment]
It looks like react-native-web-lite is a Tamagui dependency.

```"@tamagui/static@npm:1.12.2":
  version: 1.12.2
  resolution: "@tamagui/static@npm:1.12.2"
  dependencies:
    "@babel/core": ^7.19.6
    "@babel/generator": ^7.19.6
    "@babel/helper-plugin-utils": ^7.19.0
    "@babel/parser": ^7.19.6
    "@babel/plugin-transform-react-jsx": ^7.19.0
    "@babel/runtime": ^7.19.4
    "@babel/traverse": ^7.19.6
    "@tamagui/build": 1.12.2
    "@tamagui/cli-color": 1.12.2
    "@tamagui/config-default-node": 1.12.2
    "@tamagui/core-node": 1.12.2
    "@tamagui/fake-react-native": 1.12.2
    "@tamagui/helpers": 1.12.2
    "@tamagui/helpers-node": 1.12.2
    "@tamagui/proxy-worm": 1.12.2
    "@tamagui/shorthands": 1.12.2
    "@tamagui/types": 1.12.2
    babel-literal-to-ast: ^2.1.0
    esbuild: ^0.17.5
    esbuild-register: ^3.4.2
    find-cache-dir: ^3.3.2
    find-root: ^1.1.0
    fs-extra: ^11.1.0
    invariant: ^2.2.4
    lodash: ^4.17.21
    react-native-web-internals: 1.12.2
    react-native-web-lite: 1.12.2```

**Comment by nandorojo** [comment]
check your next config file to see if you’re using it

**Comment by deggertsen** [comment]
It is set to false in the next config. So I guess that's not it. 

I did try editing the solito image files to use the .native pattern instead of .web and it fixed the issue. So it probably is something to do with react-native-web-lite even though it isn't active. Not totally sure about that, but that's my current theory.
<img width="182" alt="image" src="https://user-images.githubusercontent.com/3967142/230690110-d006a5b2-3012-4780-8f40-c2a3af79cc9f.png">

**Comment by tomeddie** [comment]
Where did you create the image files at @deggertsen?  I've run into this same issue and haven't been able to resolve it yet.  Also are they named or default exports?

**Comment by deggertsen** [comment]
> Where did you create the image files at @deggertsen? I've run into this same issue and haven't been able to resolve it yet. Also are they named or default exports?

I am not currently using SolitoImage due to this issue. I'm not exactly sure what you are asking. For me, this is about using SolitoImage as an Image component in my Tamagui UI. When I try to do that, I get this error unless I manually modify the files like I mentioned in my last comment.

**Comment by dohomi** [comment]
a shot in the dark but I run SolitoImage in the tamagui kitchen sink in one example:
https://tamagui-extras.vercel.app/?path=/docs/core-content-avatar--documentation#with-solito-image
maybe you guys can compare your setup with the kitchen sink and see where your's is different. In my other non-public app I run SolitoImage as well without any issues. I remember in the past that I had to use the `next-transpile-modules` instead of the built in - maybe worth a shot.

**Comment by matthewmturner** [comment]
I have same error with `yarn web` as OP when using expo-image.  tamagui v1.15.19. Haven't had the chance to dig much into  it yet - just using tamagui `Image` for now which is working.

**Comment by matthewmturner** [comment]
Interesting, i get the same error when trying to use `Video` from `expo-av`

**Comment by dohomi** [comment]
@matthewmturner I use expo-av inside the kitchen sink: https://tamagui-extras.vercel.app/?path=/docs/video-video--documentation have a look maybe it helps with your setup

**Comment by clayrisser** [comment]
Any suggestions on the actual root cause of this issue?

**Comment by matthewmturner** [comment]
@dohomi Okay I'll give it a look.

**Comment by VladyslavKochetkov** [comment]
Running into this issue as well

**Comment by VladyslavKochetkov** [comment]
I'm pretty sure the error lies here.

https://github.com/tamagui/tamagui/blob/0c377aa5d7a2f2d3c32e96431dcec52a366aa708/packages/web/src/createTamagui.ts#L80.

`configIn.tokens[key][skey]` fails to resolve to anything meaningful

**Comment by felicio** [comment]
> Interesting, i get the same error when trying to use `Video` from `expo-av`

@matthewmturner, and in our case it was `expo-blur`. For now, I patched it with https://github.com/status-im/status-web/commit/fb4f97d4e05797a9ff7b3b02226a69a9c08a695e after debugging like so https://github.com/status-im/status-web/pull/383#discussion_r1176367254.

**Comment by matthewmturner** [comment]
@felicio awesome thanks. Going to try that.

**Comment by natew** [comment]
Hey guys, going to check this out soon

**Comment by matthewmturner** [comment]
@deggertsen Were you originally trying to use lib from ui package? That's where I had been trying to use and was having issues

**Comment by natew** [comment]
Have a fix for this in the next release.

**Comment by matthewmturner** [comment]
@natew Awesome, thanks! What was the issue?

**Comment by deggertsen** [comment]
> 

Yes, I was. It seems that when we merged the UI package with the APP package that this issue went away. Looking forward to seeing what nate's solution is.

**Comment by deggertsen** [comment]
> @deggertsen Were you originally trying to use lib from ui package? That's where I had been trying to use and was having issues

Yes, I was. It seems that when we merged the UI package with the APP package that this issue went away. Looking forward to seeing what nate's solution is.

**Comment by benschac** [comment]
downgrading expo sdk to 47 might also fix the issue: https://github.com/expo/expo/tree/main/packages/expo-image#installation

**Comment by la55u** [comment]
> downgrading expo sdk to 47 might also fix the issue
It was an outdated readme, they fixed it recently, so it should work with Expo SDK 48:
https://github.com/expo/expo/pull/22508/files

**Comment by natew** [comment]
In the latest release .web and .native also load properly into the compiler depending on mode. 

Let me know if this is still relevant.

**Comment by matthewmturner** [comment]
im still having issue with using expo-image in packages/ui but now with a new error (I am transpiring expo-image).

anyone else have luck getting expo-image to work?

<img width="1369" alt="image" src="https://github.com/tamagui/tamagui/assets/22136083/4d5fc2a4-2baf-4c34-8b5f-ad8efc9e7b10">
